/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayRouteImport } from './routes/play'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLobbyRouteImport } from './routes/_authenticated.lobby'
import { Route as AuthenticatedOnlineGameIdRouteImport } from './routes/_authenticated.online.$gameId'

const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLobbyRoute = AuthenticatedLobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnlineGameIdRoute =
  AuthenticatedOnlineGameIdRouteImport.update({
    id: '/online/$gameId',
    path: '/online/$gameId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/play': typeof PlayRoute
  '/lobby': typeof AuthenticatedLobbyRoute
  '/online/$gameId': typeof AuthenticatedOnlineGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/play': typeof PlayRoute
  '/lobby': typeof AuthenticatedLobbyRoute
  '/online/$gameId': typeof AuthenticatedOnlineGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/play': typeof PlayRoute
  '/_authenticated/lobby': typeof AuthenticatedLobbyRoute
  '/_authenticated/online/$gameId': typeof AuthenticatedOnlineGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/play' | '/lobby' | '/online/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/play' | '/lobby' | '/online/$gameId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/play'
    | '/_authenticated/lobby'
    | '/_authenticated/online/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlayRoute: typeof PlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lobby': {
      id: '/_authenticated/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof AuthenticatedLobbyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/online/$gameId': {
      id: '/_authenticated/online/$gameId'
      path: '/online/$gameId'
      fullPath: '/online/$gameId'
      preLoaderRoute: typeof AuthenticatedOnlineGameIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedLobbyRoute: typeof AuthenticatedLobbyRoute
  AuthenticatedOnlineGameIdRoute: typeof AuthenticatedOnlineGameIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLobbyRoute: AuthenticatedLobbyRoute,
  AuthenticatedOnlineGameIdRoute: AuthenticatedOnlineGameIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PlayRoute: PlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
